steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/heaven-493814/desklib-detector:latest', '-f', 'Dockerfile.desklib', '.']
    timeout: 1200s
    id: desklib-detector
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/heaven-493814/creative-alibi:latest', '-f', 'Dockerfile', '.']
    timeout: 300s
    id: creative-alibi
timeout: 1200s
images:
  - 'gcr.io/heaven-493814/desklib-detector:latest'
  - 'gcr.io/heaven-493814/creative-alibi:latest'
