const axios = require('axios');

async function getIamToken(apiKey) {
  try {
    const response = await axios.post(
      'https://iam.cloud.ibm.com/identity/token',
      `grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=${apiKey}`,
      {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        }
      }
    );
    return response.data.access_token;
  } catch (error) {
    throw new Error(`Gagal mendapatkan IBM IAM Token: ${error.message}`);
  }
}

/**
 * Handler untuk IBM watsonx.ai API
 * Menggunakan foundation model IBM Granite untuk mengklasifikasi teks.
 */
module.exports = async function watsonxHandler(text) {
  const apiKey = process.env.WATSONX_API_KEY;
  const projectId = process.env.WATSONX_PROJECT_ID;
  const region = process.env.WATSONX_REGION || "us-south";

  if (!apiKey || !projectId) {
    throw new Error('WATSONX_API_KEY atau WATSONX_PROJECT_ID tidak dikonfigurasi di backend.');
  }

  try {
    const token = await getIamToken(apiKey);
    const url = `https://${region}.ml.cloud.ibm.com/ml/v1/text/generation?version=2023-05-29`;

    // Prompt engineering untuk forensic AI detection
    const prompt = `You are a forensic linguistics AI expert. Analyze the following text and determine if it was written by a human or generated by an AI. Provide your analysis in strict JSON format with exactly two keys: "human_confidence" (integer 0-100 representing how confident you are it is human-written) and "reason" (short string explanation of why).

Text to analyze:
"${text}"

JSON Output:`;

    const response = await axios.post(
      url,
      {
        model_id: 'ibm/granite-13b-chat-v2', // Menggunakan IBM Granite Foundation Model
        input: prompt,
        parameters: {
          decoding_method: 'greedy',
          max_new_tokens: 150,
          repetition_penalty: 1,
          stop_sequences: ["}"]
        },
        project_id: projectId
      },
      {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        }
      }
    );

    let resultText = response.data.results[0].generated_text.trim();
    if (!resultText.endsWith("}")) {
      resultText += "}"; // Memastikan JSON valid jika terpotong oleh stop sequence
    }

    let parsed;
    try {
      parsed = JSON.parse(resultText);
    } catch (e) {
      // Fallback jika model memberikan teks ekstra di luar JSON
      const match = resultText.match(/\{[\s\S]*\}/);
      if (match) {
        parsed = JSON.parse(match[0]);
      } else {
        throw new Error(`WatsonX tidak merespons dengan JSON yang valid: ${resultText}`);
      }
    }

    return {
      human_score: parsed.human_confidence,
      feedback: parsed.reason
    };

  } catch (error) {
    if (error.response) {
      throw new Error(`IBM watsonx.ai menolak request (${error.response.status}): ${JSON.stringify(error.response.data)}`);
    } else {
      throw new Error(`Koneksi ke IBM watsonx.ai gagal: ${error.message}`);
    }
  }
};
